### ISSUE TITLE
ImportError: dlopen failed: library "libcurl-impersonate-chrome.so.4" not found On Termux

### ISSUE THREAD

**Issue by ylasgamers** [lexiforest/curl-impersonate#89] opened 2024-12-02 21:40 UTC
ImportError: dlopen failed: library "libcurl-impersonate-chrome.so.4" not found: needed by /data/data/com.termux/files/usr/lib/python3.10/site-packages/curl_cffi/_wrapper.abi3.so in namespace (default)
![photo_2024-12-03_04-38-09](https://github.com/user-attachments/assets/69272691-6ad2-4646-be09-920f7532a665)

**Comment by lexiforest** [comment] 2024-12-03 03:16
Duplicate of #42

**Closed by lexiforest** 2024-12-03 03:16 UTC
